org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC
android.useAndroidX=true
android.enableJetifier=true
# Disable incremental compilation to fix Kotlin issues
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
# Disable Kotlin daemon to avoid connection issues
kotlin.compiler.execution.strategy=in-process
org.gradle.daemon=false
# Keystore properties
storeFile=upload-keystore.jks
storePassword=Hussein7#
keyAlias=upload-key
keyPassword=Hussein7#
