// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC01PEs2nFUXrwxKLvjOKkdFHM18DBO_CA',
    appId: '1:555639744428:web:27822969de854b937d3c09',
    messagingSenderId: '555639744428',
    projectId: 'esen-notifications',
    authDomain: 'esen-notifications.firebaseapp.com',
    storageBucket: 'esen-notifications.firebasestorage.app',
    measurementId: 'G-Y80JLHBVRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKwpXThAROTbtOjmGN7KgYERHvUaKdDGw',
    appId: '1:555639744428:android:e93a3fc58589d76d7d3c09',
    messagingSenderId: '555639744428',
    projectId: 'esen-notifications',
    storageBucket: 'esen-notifications.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJfL0OUox86_InB0W_KfaKAchsmChkn_Y',
    appId: '1:415589112214:ios:75d990a4c8aa5021da65b7',
    messagingSenderId: '415589112214',
    projectId: 'hesen-notification',
    storageBucket: 'hesen-notification.appspot.com',
    iosBundleId: 'com.tv.hesen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJfL0OUox86_InB0W_KfaKAchsmChkn_Y',
    appId: '1:415589112214:ios:75d990a4c8aa5021da65b7',
    messagingSenderId: '415589112214',
    projectId: 'hesen-notification',
    storageBucket: 'hesen-notification.appspot.com',
    iosBundleId: 'com.tv.hesen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC01PEs2nFUXrwxKLvjOKkdFHM18DBO_CA',
    appId: '1:555639744428:web:f4eed4699536a1db7d3c09',
    messagingSenderId: '555639744428',
    projectId: 'esen-notifications',
    authDomain: 'esen-notifications.firebaseapp.com',
    storageBucket: 'esen-notifications.firebasestorage.app',
    measurementId: 'G-1MR20G4J19',
  );
}
