// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwH7wGp-8_8vw_GlWcvCiJRbBWKWobqM4',
    appId: '1:415589112214:web:9e46f64bc53ef4e4da65b7',
    messagingSenderId: '415589112214',
    projectId: 'hesen-notification',
    authDomain: 'hesen-notification.firebaseapp.com',
    storageBucket: 'hesen-notification.firebasestorage.app',
    measurementId: 'G-K3M054KY45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGl78gOw94X-vaFVL8uQgfDjW_DXBQNoM',
    appId: '1:415589112214:android:864a57edd3972e98da65b7',
    messagingSenderId: '415589112214',
    projectId: 'hesen-notification',
    storageBucket: 'hesen-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJfL0OUox86_InB0W_KfaKAchsmChkn_Y',
    appId: '1:415589112214:ios:75d990a4c8aa5021da65b7',
    messagingSenderId: '415589112214',
    projectId: 'hesen-notification',
    storageBucket: 'hesen-notification.firebasestorage.app',
    iosBundleId: 'com.tv.hesen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJfL0OUox86_InB0W_KfaKAchsmChkn_Y',
    appId: '1:415589112214:ios:75d990a4c8aa5021da65b7',
    messagingSenderId: '415589112214',
    projectId: 'hesen-notification',
    storageBucket: 'hesen-notification.firebasestorage.app',
    iosBundleId: 'com.tv.hesen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwH7wGp-8_8vw_GlWcvCiJRbBWKWobqM4',
    appId: '1:415589112214:web:74a477abaa98579cda65b7',
    messagingSenderId: '415589112214',
    projectId: 'hesen-notification',
    authDomain: 'hesen-notification.firebaseapp.com',
    storageBucket: 'hesen-notification.firebasestorage.app',
    measurementId: 'G-RJFYTCC6R0',
  );
}
